In [2]:
import numpy as np


In [3]:
#original vector
A=[3,4,5,5,6,7]
B=[2,2,2,8,8,8]
C=[15,15,15,15,15,15]

In [5]:
#deviations vector
print(A-np.mean(A))
print(B-np.mean(B))
print(C-np.mean(C))

[-2. -1.  0.  0.  1.  2.]
[-3. -3. -3.  3.  3.  3.]
[0. 0. 0. 0. 0. 0.]


In [6]:
#squared deviations vector
print((A-np.mean(A))**2)
print((B-np.mean(B))**2)
print((C-np.mean(C))**2)


[4. 1. 0. 0. 1. 4.]
[9. 9. 9. 9. 9. 9.]
[0. 0. 0. 0. 0. 0.]


In [7]:
#(4) average of the squared deviations vector (this is the variance) 
print(np.average((A-np.mean(A))**2))
print(np.average((B-np.mean(B))**2))
print(np.average((C-np.mean(C))**2))


1.6666666666666667
9.0
0.0


In [9]:
#(5) square root of the variance (this is the standard deviation).
print(np.sqrt(np.average((A-np.mean(A))**2)))
print(np.sqrt(np.average((B-np.mean(B))**2)))
print(np.sqrt(np.average((C-np.mean(C))**2)))

1.2909944487358056
3.0
0.0
